spring.application.name=backend

# DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ero123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#e-mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hovnaz.arm@gmail.com
spring.mail.password=ftbf hqpt aioa nutn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=mySuperSecureHS512SecretKey1234567890mySuperSecureHS512SecretKey

# Server
server.port=8080

